server.port=8083
spring.application.name=ChatMicroservice

spring.datasource.url=jdbc:postgresql://localhost:5432/chatmicrodb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

SECRET_KEY=UmF1bEVzdGVTbWVjaGVyU2lBY2Vhc3RhUGFyb2xhRXN0ZUZvYXJ0ZUdyZXVEZVNwYXJ0Cg==